version: '3.7'

services:

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - ./services/backend:/usr/src/app
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=${ENVIRONMENT}
      - APP_SETTINGS=project.config.${ENVIRONMENT}
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PWD}@db:5432/${DATABASE_NAME}
      - DATABASE_TEST_URL=postgresql://${DATABASE_USER}:${DATABASE_PWD}@db:5432/${DATABASE_NAME_TEST}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    networks:
      - api_bridge
    restart: always

  db:
    build:
      context: ./services/backend/project/db
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PWD}
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - users_data:/var/lib/postgresql/data/
    networks:
      - api_bridge

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${ENVIRONMENT}
    volumes:
      - './services/frontend/ui:/node'
      - '/node/node_modules'
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=${ENVIRONMENT}
      - BACKEND_SERVICE_URL=${BACKEND_SERVICE_URL}
      - VUE_GATEWAY_URL=${VUE_GATEWAY_URL}
      - VUE_APP_I18N_LOCALE=${VUE_APP_I18N_LOCALE}
      - VUE_APP_I18N_FALLBACK_LOCALE=${VUE_APP_I18N_FALLBACK_LOCALE}
      - VUE_APP_API_URL=${VUE_APP_API_URL}
    networks:
      - api_bridge

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4433:443
    depends_on:
      - backend
      - frontend
    networks:
      - api_bridge

networks:
  api_bridge:
    driver: bridge

volumes:
  users_data:
