export const moduleList = [
  {
    name: 'Global',
    labelKey: 'global.label',
    descriptionKey: 'global.description',
    moduleName: 'Global',
    component: null,
    data: {},
    requiredState: ['dimensioning'],
  },
  {
    name: 'Pasture',
    labelKey: 'pasture.label',
    descriptionKey: 'pasture.description',
    moduleName: 'Pasture',
    component: null,
    data: {},
  },
  {
    name: 'StockNcost',
    labelKey: 'stockNcost.label',
    descriptionKey: 'stockNcost.description',
    moduleName: 'StockNcost',
    requiredState: [],
    component: null,
    data: {},
  },
  {
    name: 'Export',
    labelKey: 'export.label',
    descriptionKey: 'export.description',
    moduleName: 'Export',
    requiredState: ['simulation'],
    component: null,
    data: {},
  },
]
