export default {
  id: '/animalProfile',
  type: 'object',
  properties: {
    batch_type_id: { type: 'integer' },
    code: { type: 'string' },
    name: { type: 'string' },
    period_MB: { type: 'string' },
    age_mois: { type: 'string' },
    sem_MB: { type: 'string' },
    weight_MB_kg: { type: 'number' },
    NEC_MB: { type: 'number' },
    lactation_duration: { type: 'string' },
    weight_birth_kg: { type: 'number' },
    milk_product_kg: { type: 'number' },
    TR: { type: 'number' },
    batch_type: {
      type: 'object',
      properties: {
        id: { type: 'integer' },
        code: { type: 'string' },
        name: { type: 'string' },
        UE_value_considered: { type: 'string' },
        UF_value_considered: { type: 'string' },
        UF_concentrated_value_considered: { type: ['string', 'null'] },
      },
      required: [
        'id',
        'code',
        'name',
        'UE_value_considered',
        'UF_value_considered',
        'UF_concentrated_value_considered',
      ],
    },
    animal_profile_periods: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          period_id: { type: 'integer' },
          CI: { type: 'number' },
          UFL: { type: 'number' },
          PDI: { type: 'number' },
          PL: { type: 'number' },
        },
        required: ['period_id', 'CI', 'UFL', 'PDI', 'PL'],
      },
    },
  },
  required: [
    'batch_type_id',
    'code',
    'name',
    'period_MB',
    'age_mois',
    'sem_MB',
    'weight_MB_kg',
    'NEC_MB',
    'lactation_duration',
    'weight_birth_kg',
    'milk_product_kg',
    'TR',
    'batch_type',
    'animal_profile_periods',
  ],
}
