export default {
  id: '/stic',
  type: 'object',
  properties: {
    climatic_year_id: { type: 'integer' },
    code: { type: 'string' },
    name: { type: 'string' },
    type: { type: 'string' },
    rendement: { type: 'string' },
    designation: { type: 'string' },
    RU: { type: 'string' },
    IN: { type: 'string' },
    ITK: { type: 'string' },
    detail_ITK: { type: 'string' },
    stic_periods: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          id: { type: 'integer' },
          period_id: { type: 'integer' },
          production: { type: 'number' },
          farming_method: { type: 'string' },
        },
        required: ['id', 'period_id', 'production', 'farming_method'],
      },
    },
    pasture_type: {
      type: 'object',
      properties: {
        id: { type: ['integer', 'null'] },
        name: { type: ['string', 'null'] },
        code: { type: ['string', 'null'] },
        nutritional_values: { $ref: '/nutritionalValues' },
      },
      required: ['id', 'name', 'code', 'nutritional_values'],
    },
  },
  required: [
    'climatic_year_id',
    'code',
    'name',
    'type',
    'rendement',
    'designation',
    'RU',
    'IN',
    'ITK',
    'detail_ITK',
    'stic_periods',
  ],
}
